core/accounts/urls.py
from django.urls import path, include
from .views import CustomLoginView, RegisterPage,send_email,weather_view

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path('send_email',send_email,name='send_email'),
    path('weather_view',weather_view,name='weather_view'),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="this is a simple blog api",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="programmer.amirrezaattary@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path(
        "", include("todo.urls")
    ),  # add this line to include the todo app urls
    path("api-auth/", include("rest_framework.urls")),
    # path('api/', include_docs_urls(title='API Sample')),
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/todo/api/v1/urls.py
from django.urls import path, include
from todo.api.v1 import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"
router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")


urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include
from . import views

app_name = "todo"

urlpatterns = [
    path("", views.TodoListView.as_view(), name="task-list"),
    path("create", views.TodoCreateView.as_view(), name="task-create"),
    path(
        "complete/<int:pk>",
        views.TodoCompleteView.as_view(),
        name="task-complete",
    ),
    path(
        "delete/<int:pk>", views.TodoDeleteView.as_view(), name="task-delete"
    ),
    path("edit/<int:pk>", views.TodoUpdateView.as_view(), name="task-update"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()
# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_api_url(self):
        return reverse("todo:api-v1:task-detail", kwargs={"pk": self.pk})

    class Meta:
        order_with_respect_to = "user"

core/todo/forms.py
from django import forms
from todo.models import Task

# Reordering Form and View


class TodoUpdateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",
    )

    class Meta:
        model = Task
        fields = ("title",)

core/todo/api/v1/views.py
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework import viewsets
from .serializers import TaskSerializer
from todo.models import Task
from .paginations import LargeResultsSetPagination
from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter


class TaskModelViewSet(viewsets.ModelViewSet):
    """getting a list of tasks and creating new task"""

    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = TaskSerializer
    pagination_class = LargeResultsSetPagination
    queryset = Task.objects.all()
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["complete"]
    search_fields = ["title"]
    ordering_fields = ["created_date"]

core/todo/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from todo.models import Task
from todo.forms import TodoUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View

# Create your views here.


class TodoListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    ordering = "-created_date"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TodoCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = "/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TodoCreateView, self).form_valid(form)


class TodoCompleteView(LoginRequiredMixin, View):
    model = Task
    success_url = "/"

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.complete = True
        object.save()
        return redirect(self.success_url)


class TodoDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = "/"


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TodoUpdateForm
    success_url = "/"

core/templates/todo/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

core/templates/todo/task_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'todo:task-list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">						
                        {{form}}
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>

core/templates/todo/task_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'todo:task-create' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'todo:task-delete' pk=task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'todo:task-complete' pk=task.id %}">Done</a></li>
              <li><a class="dropdown-item" href="{% url 'todo:task-update' pk=task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}